{% set name = "xontrib-output-search" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 661e035ece6a6a36776d1d98549fae2c4daed535497267731f7c7d9d7ea32432

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - xonsh
    - tokenize-output

test:
  commands:
    - xonsh -c "xontrib load output_search"

about:
  home: https://github.com/tokenizer/xontrib-output-search
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    Get identifiers, names, paths, URLs and words from the previous command output
    and use them for the next command in xonsh
  doc_url: https://github.com/tokenizer/xontrib-output-search/blob/master/README.md
  dev_url: https://github.com/tokenizer/xontrib-output-search

extra:
  recipe-maintainers:
    - scopatz
